config/routes.rb
Rails.application.routes.draw do
  root to: "companies#index"
  resources :policies
  resources :companies
  resources :employees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :employees, dependent: :destroy
  has_many :policies, dependent: :destroy

  validates :name, presence: true

  def company_name
    return "#{name.titleize}"
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :company
  has_and_belongs_to_many :policies

  validates :name, format: {with: /\A[a-zA-Z\s]{2,50}\z/i}, presence: true
  validates :email, format: { with: /\A[a-zA-Z0-9.\/_{|}-]+@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }, uniqueness: true
  validates :phone, numericality: true, length: { minimum: 10, maximum: 13 }, uniqueness: true, presence: true

  acts_as_nested_set
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :company_id %>
    <%= collection_select(:employee, :company_id, Company.all, :id, :company_name, prompt: true) %>
    <%#= form.text_field :company_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Company</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.phone %></td>
        <td><%= employee.company.name.titleize %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @employee.phone %>
</p>

<p>
  <strong>Company:</strong>
  <%= @employee.company.name.titleize %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/policies/_form.html.erb
<%= form_with(model: policy, local: true) do |form| %>
  <% if policy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(policy.errors.count, "error") %> prohibited this policy from being saved:</h2>

      <ul>
      <% policy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :company_id %>
    <%= collection_select(:policy, :company_id, Company.all, :id, :company_name, prompt: true) %>
    <%#= form.text_field :company_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/policies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Policies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Company</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @policies.each do |policy| %>
      <tr>
        <td><%= policy.name %></td>
        <td><%= policy.company.name.titleize %></td>
        <td><%= link_to 'Show', policy %></td>
        <td><%= link_to 'Edit', edit_policy_path(policy) %></td>
        <td><%= link_to 'Destroy', policy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Policy', new_policy_path %>

app/views/policies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @policy.name %>
</p>

<p>
  <strong>Company:</strong>
  <%= @policy.company.name.titleize %>
</p>

<%= link_to 'Edit', edit_policy_path(@policy) %> |
<%= link_to 'Back', policies_path %>